### ISSUE TITLE
brand.arizona.edu is now marcom.arizona.edu

### ISSUE THREAD

**Issue by zsmeyer** [az-digital/arizona-bootstrap#1073]
## Problem/Motivation
I got a cert error when I clicked on a link on the Arizona Bootstrap site to navigate to the brand page about colors. After a google search, it appears that maybe they changed their domain from brand.arizona.edu to marcom.arizona.edu.

I'll check in with them about the cert issue (and I guess maybe redirects?), and also ask if they'd like the links on the Arizona Bootstrap site to be updated.

**Comment by zsmeyer** [comment]
Looks like 'brand.arizona.edu' redirects automatically to the marcom domain now. I'm still trying to figure out who I can ask over there if they'd like links updated.

**Comment by zsmeyer** [comment]
I just confirmed with [Ryan Dool](https://marcom.arizona.edu/person/ryan-dool) that they'd like links updated.

**Comment by mmunro-ltrr** [comment]
The review site for the revised pull request should be available now at
https://review.digital.arizona.edu/arizona-bootstrap/issue/1073/docs/2.0/utilities/colors/
