### ISSUE TITLE
Accordion titles can overlap arrows

### ISSUE THREAD

**Issue by joshuasosa** [az-digital/arizona-bootstrap#1192]
## Problem/Motivation
Accordion titles can overlap the accordion arrows if there's too much text.

### Describe the bug
Sometimes the title of an accordion goes long or wraps on mobile. When it does, it can potentially overlap with the accordion arrows.

## Proposed resolution
Changing to something like this fixes it:
```
.accordion .card-header .btn {
  padding: .75rem 2.25rem .75rem 1.25rem;
}

.accordion .card-header .btn::after {
  right: 10px;
}

@media (min-width: 576px) {
  .accordion .card-header .btn {
    padding-right: 3rem;
  }

  .accordion .card-header .btn::after {
    right: 20px;
  }
}
```

Alternatively, could backport the way [Bootstrap 5 does it with flex](https://getbootstrap.com/docs/5.3/components/accordion/).

### Expected behavior
Accordion titles should never overlap accordion arrows.

### Example
![image](https://github.com/az-digital/arizona-bootstrap/assets/4400438/a365ffed-98d9-4910-b4ff-02073bd63cc7)

![image](https://github.com/az-digital/arizona-bootstrap/assets/4400438/e0ef0b28-77f7-4edc-8108-4d5d2099cdf0)

### Example on [it.arizona.edu](https://it.arizona.edu/it-centralization/centralizing-information-technology-services)
![image](https://github.com/az-digital/arizona-bootstrap/assets/4400438/eda5e482-e782-4e6b-b809-ba214c4948b6)
![image](https://github.com/az-digital/arizona-bootstrap/assets/4400438/df2fa844-1da9-4596-bf41-c7df3332f0b9)

### Example on lpl.arizona.edu
![image](https://github.com/az-digital/arizona-bootstrap/assets/4400438/10cba1a3-2b5b-4952-8937-b8ba52f4b0ea)

### Example solution on lpl.arizona.edu
![image](https://github.com/az-digital/arizona-bootstrap/assets/4400438/329a47f5-c530-4a11-9995-3d633f7693ec)

**Comment by mmunro-ltrr** [comment]
This may be an issue where there are different fixes for the 2.x & main branches. Investigating...

**Comment by mmunro-ltrr** [comment]
Pull request https://github.com/az-digital/arizona-bootstrap/pull/1198 closed the original issue. Moving to a Flexbox approach remains an open issue, as https://github.com/az-digital/arizona-bootstrap/issues/1207
