### ISSUE TITLE
Missing link.href and script.src attribute value on Arizona Digital CDN in docs

### ISSUE THREAD

**Issue by matt-e-king** [az-digital/arizona-bootstrap#126]
## Problem/Motivation
Got to Arizona Bootstrap [CDN docs page](https://digital.arizona.edu/arizona-bootstrap/docs/2.0/getting-started/introduction/). The highlight code for `js` and `css` CDN downloads are missing attribute values for `href` and `src`.

### Describe the bug
The highlight code for `js` and `css` CDN downloads are missing attribute values for `href` and `src`.

### To Reproduce

1. Go to ~~https://digital.arizona.edu/arizona-bootstrap/docs/0.0/getting-started/download/#arizona-digital-cdn~~ https://digital.arizona.edu/arizona-bootstrap/docs/2.0/getting-started/introduction/
2. Look at the highlighted code for "Arizona Bootstrap’s compiled CSS and JS"
3. Also go to the [homepage](https://digital.arizona.edu/arizona-bootstrap/), the card "Arizona Digital CDN" is also missing those attribute values

**Comment by danahertzberg** [comment]
Need to verify this is still an issue

**Comment by mmunro-ltrr** [comment]
At first glance, it looks like we fixed this issue a while back. Anyone still seeing the missing `href` and `src` anywhere?
