### ISSUE TITLE
Replace close icon with material design sharp close icon.

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap#127]
## Motivation
In an effort to keep our icons consistent, we should use material design sharp versions whenever necessary.

## Proposed Resolution
Change close icon here: https://review.digital.arizona.edu/arizona-bootstrap/feature/93-chris/docs/0.0/utilities/close-icon/
to use the material design icon shown here:  https://material.io/resources/icons/?icon=close&style=sharp

**Comment by danahertzberg** [comment]
Verify this is still an issue
