### ISSUE TITLE
Delete master branch from all repos

### ISSUE THREAD

**Issue by kevcooper** [az-digital/arizona-bootstrap#138]
Now that we have changed the default branch to `main`, we can delete the `master` branch.

Here is a script to delete `master` from all repos in the org (remove the "echo" to run for real):

```shell
ORG='az-digital'
for REPO in $(gh api "/orgs/${ORG}/repos" | jq -r '.[] | .name' | tr '\n' ' '); do
  echo gh api --silent -XDELETE "/repos/${ORG}/${REPO}/git/refs/heads/master"
done
```

**Comment by danahertzberg** [comment]
Kevin completed
