### ISSUE TITLE
Images missing when importing Arizona Bootstrap scss files

### ISSUE THREAD

**Issue by joeparsons** [az-digital/arizona-bootstrap#155]
## Problem/Motivation
Currently the svg images that various Arizona Bootstrap styles/components depend on _only_ exist in the `dist/css/img`directory of Arizona Bootstrap and not in the `scss` directory.  This causes problems (similar to those caused by #124) for anyone wanting to import Arizona Bootstrap's `scss` files into their own project.

### Describe the bug

@matt-e-king mentioned on #153:
> There is another use case where a project might want to ingest only the `scss` from this npm package:
> 
> ```
> // background-wrapper.scss contains all the img references
> @import "../../node_modules/arizona-bootstrap/scss/background-wrapper";
> ```
> 
> The `img` directory is not a sibiling to the `scss` files so a similar issue would occur.
> 
> I know this is only a use case as of recent conversations to use `arizona-bootstrap` as a `scss` dependency for the potential `arizona-frontend` libraries, so not sure if the responsibility should fall on this package. Either way, I'll wait for your response before approving this pull request.

## Proposed resolution
We should consider moving the style-specific images that currently live in `dist/css/img` into `scss/img` and then add something to our build process that copies (and potentially optimizes) the images into the `dist` folder as build artifacts (along with the compiled CSS files).

### Expected behavior
Arizona Bootstrap's style-specific images should be available to someone regardless of whether they are using the compiled dist assets or importing the source files.

**Comment by trackleft** [comment]
Do we think we should copy ua-bootstrap for this? https://bitbucket.org/uadigital/ua-bootstrap/src/master/src/svg/

https://bitbucket.org/uadigital/ua-bootstrap/src/50c3dd32bfdb9c3e481e35fad83b9b1150221742/tasks/stylesheets.js#lines-40:52

**Comment by trackleft** [comment]
https://review.digital.arizona.edu/arizona-bootstrap/bug/155-move-image-files-into-scss-img-folder/docs/2.0/components/background-wrappers/
