### ISSUE TITLE
Resolve pending dependabot pull requests

### ISSUE THREAD

**Issue by mmunro-ltrr** [az-digital/arizona-bootstrap#158]
## Motivation
The pending updates that dependabot suggests need reviewed.

### Is your feature request related to a problem? Please describe.
Apart from the need to apply potential bug fixes, we need to silence the dependabot messages to have a less cluttered view of what is going on.

### Pull request review
* Bump stylelint from 13.6.1 to 13.7.2 #152
  https://github.com/az-digital/arizona-bootstrap/pull/152
  matches
  https://github.com/twbs/bootstrap/pull/31726
  (into main, also included in the v4-dev 31734, see below), but does not make the analogous changes to .stylelintrc (independently, upstream has enabled the `--report-needless-disables` flag for stylelint, but that's not connected).

* Bump eslint from 7.6.0 to 7.10.0 #151
  https://github.com/az-digital/arizona-bootstrap/pull/151
  included in
  https://github.com/twbs/bootstrap/pull/31734
  (the eslint configuration is now considerably different from arizona-bootstrap).

* Bump @rollup/plugin-babel from 5.1.0 to 5.2.1 #146
  https://github.com/az-digital/arizona-bootstrap/pull/146
  included in
  https://github.com/twbs/bootstrap/pull/31624
  (which makes more extensive @rollup changes).

* Bump @rollup/plugin-node-resolve from 8.4.0 to 9.0.0 #144
  https://github.com/az-digital/arizona-bootstrap/pull/144
  included in
  https://github.com/twbs/bootstrap/pull/31624
  (which makes more extensive @rollup changes).

* Bump terser from 4.8.0 to 5.3.2 #142
  https://github.com/az-digital/arizona-bootstrap/pull/142
  not included upstream. Dependabot generated
  https://github.com/twbs/bootstrap/pull/31790
  but the maintainer noted an increase in the size of the minified files, and filed an issue with terser
  https://github.com/terser/terser/issues/822
  Although this references v5.2.0, the v4-dev branch is on 4.8.0, like arizona-bootstrap.

### Recommendation
Make a single new pull request combining #144, #146, #151, & #152, adding the upstream .stylelintrc changes. Don't merge #142, but wait for a resolution to the size increase issue.

**Comment by danahertzberg** [comment]
Close? Needs review
