### ISSUE TITLE
Document process for managing shared NetID account for TypeKit webfont project

### ISSUE THREAD

**Issue by joeparsons** [az-digital/arizona-bootstrap#160]
- Where should this documentation live (confluence?)
- Steps to manage who has access to shared account
- Steps to login to Creative Cloud / TypeKit with shared account and make changes?

## Conditions of satisfaction
- [ ] Should ‹testable condition that should be satisfied›
- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

**Comment by camikazegreen** [comment]
I've added the basic documentation for managing the Test NetId here:
[https://confluence.arizona.edu/display/UADigital/How+we+provision+Proxima+Nova+in+Arizona+Bootstrap+using+Adobe+Typekit ](https://confluence.arizona.edu/display/UADigital/How+we+provision+Proxima+Nova+in+Arizona+Bootstrap+using+Adobe+Typekit )

It might be useful for Chris to add any additional documentation that might be necessary for configuring Typekit with this NetId. 
Password info, etc.

**Comment by trackleft** [comment]
it is in Stache and everyone in the UA Digital Admins group has access.
