### ISSUE TITLE
D2L Integration

### ISSUE THREAD

**Issue by bourgeoy** [az-digital/arizona-bootstrap#176]

**Comment by bourgeoy** [comment]
We currently integrate with D2L in several ways:

- Create student accounts automatically in community D2L, and register students in correct course
- Send students to quizzes, collect the score from quiz and return that info to the original site

**Comment by joeparsons** [comment]
Closing this old issue.  Feel free to re-open if needed.  Seems like it'd be more relevant for az_quickstart than Arizona Bootstrap (?)
