### ISSUE TITLE
Add CONTRIBUTING.md file to arizona-bootstrap

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap#18]

**Comment by trackleft** [comment]
Open source example of a contributing.md file https://gist.github.com/PurpleBooth/b24679402957c63ec426
Bootstrap 4 example of contributing.md file https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md
Other example of contributing.md file within arizona digital
https://github.com/az-digital/az_quickstart/blob/master/CONTRIBUTING.md
Arizona digital Policies Repo https://github.com/az-digital/policies

**Comment by akslay** [comment]
@trackleft  Would this expand upon the /about/get-involved/ page we have on the documentation site? Or would this just be an MD file for the repo specifically, rather than the documentation site?

**Comment by trackleft** [comment]
@akslay this is a developer's guide in the repo for how to contribute back to the project, with specific instructions, we can link to the repo CONTRIBUTING.md file within bootstrap docs, or link to bootstrap docs within CONTRIBUTING.md
https://github.com/az-digital/az_quickstart/blob/master/CONTRIBUTING.md
