### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap#20]
Add readme for arizona bootstrap.
Here is the bootstrap 4 readme https://github.com/twbs/bootstrap/blob/master/README.md
We should highlight the differences between BS4 and AZBoostrap, possibly link to ua-bootstrap.

**Comment by barrettbaffert** [comment]
@trackleft do you think this task can be closed?

**Comment by trackleft** [comment]
We don't yet have a readme https://github.com/az-digital/arizona-bootstrap

**Comment by barrettbaffert** [comment]
Haha sorry... I didn't pay attention to what repo I was looking at 🕵
