### ISSUE TITLE
Sourcing New Icons

### ISSUE THREAD

**Issue by geijutsuka** [az-digital/arizona-bootstrap#207]
## Contribution of additional icons
There are various design/marketing units on campus we can utilize to source more icons. We can reach out to EM Marketing and @RyanDool to see if they have a repository of icons or at least some svgs we can utilize for the set of Arizona Icons.

## Conditions of satisfaction
- [ ] A process to contribute is documented
- [x] Candidate icons are identified
- [ ] A recommended next step is documented
- [ ] An estimate of time and effort is provided for the recommendation

**Comment by trackleft** [comment]
Process to contribute. Need documentation on using Ico moon
Release process can mirror arizona bootstrap in the future
Current release process is manual.
Next step is to make a pipeline mirroring arizona bootstrap.

**Comment by joeparsons** [comment]
Going to close this as completed since we decided to adopt Material icons some time ago and we also have our separate AZ Icons repo now.

**Comment by joeparsons** [comment]
If new icons are still needed or need to be added, it would probably be best to create a new issue in the AZ Icons repo.
