### ISSUE TITLE
Main navigation font weight, whitespace, and scrolling bugs

### ISSUE THREAD

**Issue by geijutsuka** [az-digital/arizona-bootstrap#223]
## Problem/Motivation
Larger screen size main navigation changed to be inaccessible after the off-canvas PR was merged and it was found that mobile navigation is not scrolling.

### Description and proposed solutions (screenshots further below)
Before: https://dev-sasg-registrar.pantheonsite.io
After: http://azqs-sasg-registrar.pantheonsite.io

#### Font weight:
"Font weight for the added off-canvas nav is impacting the desktop breakpoint and making it very difficult to read. Font weight change needs to be moved to a mobile media query." - @akslay 
Specifically this CSS rule: `.navbar-offcanvas .dropdown-menu .dropdown-item`

#### Whitespace:
Whitespace property was changed to have text wrap. This declaration will need to be added to a media query.

#### Scrolling:
Mobile nav is not scrolling (unsure of fix).

### To Reproduce
Create a navigation menu with several items and dropdowns.

##  Screenshots
<img width="1145" alt="reg_update_before" src="https://user-images.githubusercontent.com/1971196/108565976-e1a76d00-72c2-11eb-859b-37e8dcec7391.png">
<img width="1143" alt="reg_update_after" src="https://user-images.githubusercontent.com/1971196/108566017-f257e300-72c2-11eb-9583-800d14956f26.png">

**Comment by trackleft** [comment]
As a note, this site: http://azqs-sasg-registrar.pantheonsite.io
Does not look like this: https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/navbar-off-canvas/

**Comment by akslay** [comment]
I've attached a .txt file with CSS that will fix all the nav bugs in this ticket. 
[azbootstrap_nav_fixes.txt](https://github.com/az-digital/arizona-bootstrap/files/6104844/azbootstrap_nav_fixes.txt)
