### ISSUE TITLE
Browser support to include Edge on Mac

### ISSUE THREAD

**Issue by its-me-mario** [az-digital/arizona-bootstrap#226]
## Problem/Motivation
It appears that using Microsoft Edge on a Mac is not applicable.

### Describe the bug
Microsoft Edge on Mac appears to not be supported, or N/A to be specific. Since Microsoft released Edge for Mac in early 2020, this should be supported

### To Reproduce

1. Go to [Browsers and devices > Desktop Browsers](https://digital.arizona.edu/arizona-bootstrap/docs/2.0/getting-started/browsers-devices/#desktop-browsers)
2. See under Microsoft Edge and Mac, it says: N/A

## Proposed resolution
Change status to "Supported"

### Expected behavior
I'd expect this to be supported since I currently use this combination with no serious issues.

**Comment by mmunro-ltrr** [comment]
Closed by PR #227
