### ISSUE TITLE
Card titles break word

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/arizona-bootstrap#243]
_SASG found original bug_

Longer card titles wrap instead of breaking the whole word to the next line.

![image.png](https://images.zenhubusercontent.com/5eb9d10a2b1f2c51836b60e3/a7c9291a-d5f0-4c18-8349-0d765ae8a531)

**Comment by smayden** [comment]
I'm having trouble recreating this issue on a current QS2 Probo build. The only way I can get words to wrap to the next line is when the word length is longer than the column width (especially when we have 4 cards and a sidebar menu). Even then though the text from the provided screenshot did not wrap in the same way.

Thoughts on whether this issue still needs to be addressed? @geijutsuka @akslay Can you point to live examples on the Registrar site?

**Comment by danahertzberg** [comment]
@smayden Even if the only issue is that a word is too long for the container, I would propose we still implement a hyphenated solution instead of just wrapping without context.

**Comment by danahertzberg** [comment]
After discussion, Shoshana and I agree the word break is acting as expected. We propose adding a new class to bootstrap to allow specific words to be hyphenated when needed.

```
.auto-hyphen {
hyphens: auto;
}
```
