### ISSUE TITLE
Tables do not have styling

### ISSUE THREAD

**Issue by smayden** [az-digital/arizona-bootstrap#280]
Tables are not currently styled (or at least not similarly to QS 1)

Current styling happening in QS2:
![image](https://user-images.githubusercontent.com/10873398/118370162-4dfcda00-b55b-11eb-99c2-a1ce5eaf2e34.png)

Styling in QS1:
![image](https://user-images.githubusercontent.com/10873398/118370186-72f14d00-b55b-11eb-993d-cd2595fe7a93.png)

## Conditions of satisfaction
- [ ] Match styles in QS1

**Comment by danahertzberg** [comment]
I remember we had a discussion a while ago that we would adopt the Bootstrap 4 styling of tables: https://digital.arizona.edu/arizona-bootstrap/docs/2.0/content/tables/

Hopefully we just need to update a reference to the BS classes somewhere.

**Comment by mmunro-ltrr** [comment]
So there really doesn't need to be a change in arizona-bootstrap for this?

**Comment by danahertzberg** [comment]
@mmunro-ltrr Hopefully not. So you're right this might need to move over to the az_quickstart repo.

**Comment by danahertzberg** [comment]
Issue moved to [az-digital/az_quickstart #795](https://github.com/az-digital/az_quickstart/issues/795) via [**ZenHub**](https://www.zenhub.com/)
