### ISSUE TITLE
Accordion icons disappear in Safari

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap#316]
## Problem/Motivation
![image](https://user-images.githubusercontent.com/1023167/122977091-d3895c00-d349-11eb-9c87-0768c8314608.png)

### Describe the bug
In some browsers (ehm.. Safari) icons set as ligatures in the content property of pseudo element seems to not translate well.

### To Reproduce
View accordion component in safari, notice that the icon is missing.

## Proposed resolution
Update `.accordion .card-header .btn:after` properties to include `font-variant-ligatures: no-common-ligatures;` 

### Expected behavior
Icons should then appear as expected.

### Desktop (please complete the following information):
 - OS: Mac
 - Browser [Safari]

**Comment by priyanshk20** [comment]
Can I do this task?

**Comment by trackleft** [comment]
This is a high priority ticket, if you want to take it please make a fork and merge request as soon as possible.
https://github.com/az-digital/arizona-bootstrap/blob/main/CONTRIBUTING.md

**Comment by priyanshk20** [comment]
Okay doing it ASAP
