### ISSUE TITLE
Add hover states for all cards (clickable cards)

### ISSUE THREAD

**Issue by akslay** [az-digital/arizona-bootstrap#353]
## Motivation
We will be adding "clickable card" functionality to Arizona Quickstart 2.0 (https://github.com/az-digital/az_quickstart/issues/737). This means that each style of card needs a hover state. 

## Proposed Resolution

- [x] For standard cards with background colors, leverage the built-in SCSS `darken()` function, which will darken the given background-color.
- [x] For Landing Grid cards, match the mockup from az-digital/az_quickstart#982
- [x] For all card types, add the visual indicator arrow to the card
- [x] For all card types, update/add documentation pertaining to "clickable cards"
        - The documentation for [Borderless Cards](https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/card/#borderless) is no longer accurate as of AZQS 2.0
        - Add a "Clickable Card" section to each card style (background and color, border, borderless, landing grid)
- [x] Utilize the Stretched Link utility class

## Relevant Screenshots

https://user-images.githubusercontent.com/52931751/131753327-9b6c9b73-ce4c-4712-8b47-35788a248fc0.mov

**Comment by its-me-mario** [comment]
@akslay I'd like to recommend that we update the focus indicator for keyboard users. I made [this codepen](https://codepen.io/itsmemario/pen/vYZGQzg?editors=1100) to demonstrate. It's not critical but it might be a better experience if users could see that the entire card is in focus.

**Comment by akslay** [comment]
Thanks for the recommendation @its-me-mario (: So it looks like (basically) add a box-shadow in addition to the background color change on the clickable cards?

**Comment by its-me-mario** [comment]
@akslay The box shadow is optional. The real keyboard focus parts are the **::before** pseudo elements and the **outline** property changes.

The **.card:hover, .card:focus-within** is one (accessible) way to make a clickable card. I went with that background color just for consistency with existing "active" UI patterns used by the nav but I'd be okay with other options if it makes sense to everyone else.

**Comment by akslay** [comment]
@its-me-mario So the clickable cards actually won't have physical buttons on them, so we won't be able to apply the pseudo element in this case. But we should be able to add in the outline.

**Comment by its-me-mario** [comment]
Ah ok, that will work. I thought the arrows in the example would be a link and wanted to make sure the entire card would be in focus if the user focused on the link. Also, just having the same styling as the hover can work too (without an outline) as long as the focus state changes and there's a noticeable visual difference between states.

There are other [considerations](https://inclusive-components.design/cards/) around usability and accessibility. Probably the biggest one is when you wrap the entire card with an <a>, because links become less useful to screen readers because it reads all the card text as the link text.

**Comment by akslay** [comment]
Yeah I was hoping to be able to leverage the [stretched link](https://digital.arizona.edu/arizona-bootstrap/docs/2.0/utilities/stretched-link/) (same as the pseudo element you showed earlier) utility for the redesign, so that we can improve the screen reader experience. I was thinking of making the "link" be the card's title (so that the title, rather than the entire card is read aloud on the screen reader). 

But unfortunately the decision was that Quickstart 2.0 isn't going to require the "cart title" field on its cards, so there wouldn't be anything for us to target as that stretched link, and the entire body would become the target. :(

**Comment by its-me-mario** [comment]
Ha, I never noticed we had that utility.

Since I don't work with Quickstart / Drupal, I don't know about the constraints. Thank you for you patience. 😄

**Comment by akslay** [comment]
No problem at all. 🙂 I'd rather cover all the bases so the input/feedback is much appreciated.

**Comment by akslay** [comment]
It might be good to at least mention in the documentation, though, that the card _can_ be used with the stretched link utility, as a means of improving accessibility/screen reader experience. Since some people do use Bootstrap outside of Quickstart, and could benefit from the improvement.

**Comment by its-me-mario** [comment]
Yeah, for sure. Maybe it can be included as an example, since it seems like a common pattern people might consider. I'd be concerned that if people don't know about the accessibility issues they would just wrap everything in a <a> because why not.
It's a different if there are constraints, because at least you know why and it can be considered (for Quickstart in this case) for the right reasons.

**Comment by trackleft** [comment]
@akslay do you think we could add a field for screen reader text, and still use the stretched link class?

https://www.deque.com/blog/text-links-practices-screen-readers/

**Comment by its-me-mario** [comment]
Thanks Chris, that would be great!

Just wanted to suggest that we may want to avoid using the title attribute in favor of aria-label on links for [reason 1](https://www.24a11y.com/2017/the-trials-and-tribulations-of-the-title-attribute/#anchor-links--form-fields) and [2](https://axesslab.com/title-texts-suck/#6-screen-readers-read-title-texts-inconsistently).

Also, NVDA improved aria-label support in 2015 as mentioned in that [Deque link](https://www.deque.com/blog/text-links-practices-screen-readers/) under the "Update" and "Results" sections. [These results](https://www.powermapper.com/tests/screen-readers/aria/) also show pretty good support for aria-label from 2019.

**Comment by akslay** [comment]
@trackleft I think rather than adding an extra field I might be in favor of just making the existing card title field required for the clickable cards only, and then wrapping the anchor tag around the card title. Especially since the clickable cards won't have a typical card link at the bottom, in favor of the visual arrow.

**Comment by akslay** [comment]
@tadean @joeparsons @smayden @camikazegreen @geijutsuka @mmunro-ltrr 

Does anyone else have a preference/feedback/thoughts with regards to how we should handle the clickable cards in Quickstart (which will determine how we document it in Bootstrap)? It would be nice if we could leverage the Stretched Link utility that's built into Bootstrap, since it improves screen reader experience. But that would entail either adding another field (as Chris mentioned) or making an existing field required so we have something to wrap an anchor tag around for the stretched link.

**Comment by akslay** [comment]
**Decision after conversation in workshop 2021/09/08:** 
We will put the visual arrow inside the anchor tag and utilize the stretched link utility that's built into Bootstrap. We will add the title and aria attributes to the link tag but also run that by the DRC to see whether they think we should use one or both attributes. 

On the Quickstart side, we will utilize the link text field as the anchor title/aria, rather than making the card title required.

**Comment by joeparsons** [comment]
We're going to close this for now.  If more clickable card options are needed we can definitely re-open this issue and its associated PR.
