### ISSUE TITLE
The process for updating dev dependencies is undocumented.

### ISSUE THREAD

**Issue by mmunro-ltrr** [az-digital/arizona-bootstrap#403]
The best practices for dealing with dependabot updates to `package.json` and upstream Twitter Bootstrap dev dependency updates needs documented. Unfortunately, complete automation isn't possible, since dependabot happily suggests some version number bumps that conflict with Twitter Bootstrap's deliberate pinning to specific versions. In the next few months there may be more potential conflicts in the JavaScript tooling than usual, because at least one major source of NPM packages is pushing for adoption of ESM over CommonJS and other systems for importing modules.

**Comment by mmunro-ltrr** [comment]
Twitter Bootstrap has used an additional tool to suggest updates to package versions, going back five years (before dependabot suggestions were available). It's  npm-check-updates (providing the `ncu` command), from
https://github.com/raineorshine/npm-check-updates
A major refactoring of the build system introduced it in the npm script `maintenance-dependencies`
https://github.com/twbs/bootstrap/pull/22045
then a subsequent  routine update
https://github.com/twbs/bootstrap/pull/27367
renamed the script to `update-deps`.

Revised Arizona Bootstrap dev dependency documentation might use this.

**Comment by joeparsons** [comment]
Closing this since these things aren't as big of a priority now that we're using dependabot.
