### ISSUE TITLE
Flexbox column doesn't work as expected for bottom borders in some cases.

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap#430]
## Problem/Motivation
Bottom borders for `a` child elements of `.d-flex` elements and with `split-md-2-col flex-column` as ancestors don't always appear correctly.

### Describe the bug

Consider a two-column list of links with an unknown number of items.
```
<ul class="split-md-2-col nav flex-column nav-utility clearfix">
      <li class="d-flex px-0 nav-item">
           <a href="/about" class="bg-transparent nav-link nav-link--about" >About</a>
       </li>
       <li class="d-flex px-0 nav-item">
           <a href="/home" class="bg-transparent nav-link nav-link--about" >Home</a>
      </li>
      <li class="d-flex px-0 nav-item">
           <a href="/resources" class="bg-transparent nav-link nav-link--about">Resources</a>
       </li>
</ul>
```
See [Codepen](https://codepen.io/trackleft/pen/dyXqVja)
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1023167/155180718-ed85af70-e879-4534-aae0-ac6015d5c411.png">

### To Reproduce
Add a list with the code above and an uneven number of links to reproduce the issue.
https://codepen.io/trackleft/pen/dyXqVja

## Proposed resolution
Find a workaround or fix for this type of listing.

**Comment by joeparsons** [comment]
We're going to close this for now.  Please feel free to re-open if this is still an issue.
