### ISSUE TITLE
Add Bootstrap releases document

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/arizona-bootstrap#441]
## Motivation
I want a definition for semantic releases on Arizona Bootstrap

## Proposed Resolution
Add new releases doc to bootstrap repo with definitions (potentially similar to quickstart)

**Comment by mmunro-ltrr** [comment]
See #479 (automation takes care of most of the process for an actual release, more work is needed for the routine pull request merges & updates just before this).

**Comment by mmunro-ltrr** [comment]
The az_quickstart releases document is at https://github.com/az-digital/az_quickstart/blob/main/RELEASES.md (giving the semanic versioning conventions).
