### ISSUE TITLE
H* Card Headers have extra top margin

### ISSUE THREAD

**Issue by MarkFischer** [az-digital/arizona-bootstrap#449]
## Problem/Motivation
When using a header element, ie h5, as a card-header, the top margin from the heading is still applied, leaving a space between the top of the card and the header.

### Describe the bug
See https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/card/#header-and-footer under the "Card headers can be styled by adding .card-header to <h*> elements." section. There is a margin separating the top of the Card from the Header. Compare to the <div> example above and you can see there is no margin there.

## Proposed resolution
The margin-top should be set to 0 for the card-header class, similar to how the margin-bottom is set to 0 currently.

### Expected behavior
The header should be flush against the top of the card.

### Desktop (please complete the following information):
 - OS: Mac
 - Browser Safari, Firefox, Chrome

**Comment by MarkFischer** [comment]
I'm a newb as to how all this CSS gets built. I _think_ that we could just add a `margin-top: 0;` statement to the `.card-header` selector in https://github.com/MarkFischer/arizona-bootstrap/blob/v2.0.13/dist/css/arizona-bootstrap.css#L4584

**Comment by mmunro-ltrr** [comment]
The CSS is actually derived: I'll take a look at how the SCSS would change.

**Comment by joeparsons** [comment]
Closing this issue since it seems like margin utility classes could provide a viable workaround : https://digital.arizona.edu/arizona-bootstrap/docs/2.0/utilities/spacing/#notation

Feel free to re-open if this needs more conversation.
