### ISSUE TITLE
Add az-vimeo icon to bootstrap docs.

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap#457]
## Conditions of satisfaction
- [ ] vimeo icon should be here: https://digital.arizona.edu/arizona-bootstrap/docs/2.0/icons/

**Comment by michaelhagedon** [comment]
Oh yeah, good call -- I thought about this during az-digital/az-icons#17, but then forgot!

**Comment by joeparsons** [comment]
Closing this as a duplicate of #1153
