### ISSUE TITLE
Linkinator detects many broken links within the arizona bootstrap docs.

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap#459]
## Problem/Motivation
While working on a different ticket, I found that linkinator was detecting many broken links on our docs site.
We need to fix these in order to push updates to our doc site, also, broken links aren't good to have on your site generally.

### To Reproduce
Build arizona-bootstrap locally
Change the `docs-linkinator` command in package.json to this `    "docs-linkinator": "linkinator _site --recurse --verbosity error",`
Run `npm run docs`
See errors

## Proposed resolution
Fix broken links.

**Comment by mmunro-ltrr** [comment]
The present line in package.json is
```
"docs-linkinator": "linkinator _site --recurse --skip \"^(?!http://localhost)\" --verbosity error",
```
blindly copying what upstream Twitter Bootstrap has on the v4-dev branch; the main branch there no longer invokes linkinator from the package.json scripts at all, but hives it off to a GitHub Action https://github.com/twbs/bootstrap/pull/35573
But if Arizona Bootstrap is really getting many broken links in the docs obviously a change of course is needed.

**Comment by trackleft** [comment]
Thanks, @mmunro-ltrr I made a PR if you don't mind reviewing it https://github.com/az-digital/arizona-bootstrap/pull/460
