### ISSUE TITLE
Arizona Bootstrap CI

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/arizona-bootstrap#46]

**Comment by joeparsons** [comment]
## Needed CI / Automation

### Pull Request Checks

- Build documentation site artifact
- Deploy documentation site artifact to reviewsite
- Publish/attach link to review site on PR (via GitHub Checks API?)

####Future improvements

- BackstopJS visual regression test?
- Publish/attach link to BackstopJS results on PR?
- Lighthouse accessibility check?
- Publish/attach link to Lighthouse results on PR?
- Notify slack channels? (might not be needed if we attach link to PR)

### Merge Tasks

- Build dist assets
- Build documentation site artifact
- Push dist assets to ‘master’ CDN directory
- Push documentation site artifact to ‘master’ documentation site
- Invalidate assets CDN cache for ‘master’ directory
- Invalidate CDN cache for ‘master’ documentation site

### Release Tasks

- Update version info in package.json? Tag release?
- Build dist assets
- Push dist assets to release-specific CDN directory
- Push dist assets to ‘latest’ CDN directory
- Invalidate CDN cache for ‘latest’ directory
- Generate Quickstart PR to update packaged copy of Bootstrap
