### ISSUE TITLE
Re-add image properties from UA Bootstrap

### ISSUE THREAD

**Issue by joshuasosa** [az-digital/arizona-bootstrap#462]
## Problem/Motivation
Unless otherwise noted, styling from UA Bootstrap to AZ Bootstrap should be similar.

### Describe the bug
After completing a migration for my department, some images were expanding outside the content space when they were too big for the space they're given on the page.

### To Reproduce
Set up a page that uses 'container' and add an image that's wider than the container's width. The image should display wider than the content width.

## Proposed resolution
Either add verbiage about images no longer having the same properties as in UA Bootstrap and need to use `.img-fluid`, or re-add the same properties.

Specifically, something like the following may be added which exists in UABS:
```css
img {
  max-width: 100%;
  height: auto;
}
```

**Comment by joeparsons** [comment]
Discussed this issue in our 2024-07-10 workshop and decided that fixing this at this stage of the AZBS 2.0.x lifecycle is probably risks causing more problems than it solves.  The `.img-fluid` utility class seems like the best recommendation available for this.
