### ISSUE TITLE
Allow backporting bugfix and security updates to multiple minor release versions

### ISSUE THREAD

**Issue by mmunro-ltrr** [az-digital/arizona-bootstrap#512]
Currently all releases of Arizona Bootstrap are patch version bumps of a single minor version, `2.0.x`. Once there are multiple minor versions (2.0, 2.1, 2.2...), possibly a bugfix or security update to the development version should be applied not only to a new release of the highest numbered minor version, but to patch releases of lower numbered minor versions as well.

When something is referencing the built artifacts (CSS and JavaScript) in the CDN, it should pick up critical changes to a particular minor version of Arizona Bootstrap without having to explicitly specify a version number (by some mechanism such as a `latest` patch version).

We need an investigation of the best mechanism to implement these requirements in the GitHub repository and AWS S3 + CloudFront CDN.

**Comment by joeparsons** [comment]
@mmunro-ltrr said this issue is obsolte.
