### ISSUE TITLE
The Java support needed for one of the linting checks is deprecated.

### ISSUE THREAD

**Issue by mmunro-ltrr** [az-digital/arizona-bootstrap#513]
The linting checks in arizona-bootstrap include the Nu Html Checker (vnu-jar), which needs a Java environment to run. To standardize this in a way that works for local development as well as on GitHub actions. The Dockerfile includes this by lifting it from a pre-built standard OpenJDK Docker image, but this is now deprecated
https://github.com/docker-library/openjdk/issues/505

## Conditions of satisfaction
Some other mechanism should include an actively maintained Java environment to support the vnu-jar checker.

**Comment by tellison** [comment]
The recommended replacements are the [official images of Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin)

**Comment by mmunro-ltrr** [comment]
@tellison: thanks for the advice — I had looked at those images, but we are currently doing something strange with a
```
COPY --from=openjdk:11.0.15-jre-slim-bullseye "$JAVA_HOME" "$JAVA_HOME"
```
in our Dockerfile to lift just part of the old OpenJDK image, relying on both being based on Debian Bullseye. It's probably time to opt for something less fragile instead.
