### ISSUE TITLE
Review sites are not deployed from some pull requests

### ISSUE THREAD

**Issue by mmunro-ltrr** [az-digital/arizona-bootstrap#536]
## Problem/Motivation
Review the history of GitHub Actions on this repository: many deployments to the AWS review site fail at an early stage, when handling the `package-lock.json` file.

### Describe the bug
In many cases the lockfile should be unmodified, but committing a changed version causes a permission error.

## Proposed resolution
Investigate the use of the `npm ci` command in place of `npm install` in some contexts.
https://docs.npmjs.com/cli/v8/commands/npm-ci

**Comment by joeparsons** [comment]
Closing this for now since we haven't seen this problem lately.
