### ISSUE TITLE
MVP GitHub Actions for AZ Bootstrap Releases

### ISSUE THREAD

**Issue by joeparsons** [az-digital/arizona-bootstrap#60]
## User Story(s)
As an _admin_ of the Arizona Digital team, I'd like to be able to manually trigger a CI job (GitHub Action) that automatically performs whatever tasks are necessary to create a new AZ Bootstrap release in order to make it easier to release the latest AZ Bootstrap improvements.
…

## Conditions of satisfaction
Should add GitHub Actions configuration that provides a job/workflow which can be triggered manually by Arizona Digital team _admins_ that does the following:
- [x] Updates version info in package.json
- [x] Creates a release commit
- [x] Creates and pushes git tag
- [x] Builds dist assets
- [ ] Builds documentation site artifact
- [x] Deploys dist assets to release-specific CDN directory
- [x] Deploys dist assets to ‘latest’ CDN directory
- [ ] Deploys documentation site artifact to prod documentation site
- [x] Invalidates CDN cache for ‘latest’ directory
- [ ] Updates arizona-bootstrap-packagist repo (@kevcooper suggested adding a GitHub actions workflow to the `arizona-bootstrap-packagist` repo that can be triggered by an `arizona-bootstrap` release/tag)
- [ ] Creates Quickstart PR to update arizona-bootstrap-packagist version (?)

**Comment by mschmeling14** [comment]
How will releases for Bootstrap be created?
