### ISSUE TITLE
Arizona Bootstrap 2.0.20 Release Plan

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap#649]
Cherry-pick from 2.x list : 
~~6c09c7bbe7ccb3e732eb585dc14d7fb3844c6a15 (https://github.com/az-digital/arizona-bootstrap/pull/611)~~
~~58a0e6d43dd594c6744f8020534b3c6e3f1e7ef6 (https://github.com/az-digital/arizona-bootstrap/pull/626)~~

Merge: 
https://github.com/az-digital/arizona-bootstrap/pull/648
https://github.com/az-digital/arizona-bootstrap/pull/640

Merge after last release of 2.x version from `main` in the following order:
1. https://github.com/az-digital/arizona-bootstrap/pull/641
2. https://github.com/az-digital/az_quickstart/pull/2123

**Comment by joeparsons** [comment]
https://github.com/az-digital/arizona-bootstrap/releases/tag/v2.0.20
