### ISSUE TITLE
Use major versions for community Github Actions

### ISSUE THREAD

**Issue by jwmoore1** [az-digital/arizona-bootstrap#654]
## Motivation
Similar to how we changed the [Github Actions in Quickstart](https://github.com/az-digital/az_quickstart/issues/2190) to reference major versions, we should apply the same idea for Arizona Bootstrap.

### Describe the solution you'd like
Reference major versions of the community Github Actions we use in Arizona Bootstrap.

**Comment by joeparsons** [comment]
I think this is resolved now after several dependabot updates.
