### ISSUE TITLE
The names assigned to the review sites in S3 do not always match the arizona-bootstrap branch names.

### ISSUE THREAD

**Issue by mmunro-ltrr** [az-digital/arizona-bootstrap#72]
## Problem/Motivation
Rather than labelled numbers numbers referencing an issue (bug/..., feature/...) some of the review sites are being identified as ../merge.

### Describe the bug
The interpretation of the `GITHUB_REF` environment variable in the action os incorrect.

### Additional context
See the comments on
https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions

**Comment by mmunro-ltrr** [comment]
The canonical documentation for how various different workflow-triggering events set `GITHUB_REF` is at
https://help.github.com/en/actions/reference/events-that-trigger-workflows
and for `pull_request` that's supposed to be the PR merge branch, with the format
`refs/pull/:prNumber/merge`.
So when we trim off the prefix matching the pattern `refs/*/` we're left with the `:prNumber/merge` part.

**Comment by joeparsons** [comment]
Perhaps we could have two conditional steps (one for push events and one for pull requests) that each populate that TRIMMED_REF variable with the appropriate value?
