### ISSUE TITLE
Update dropdown menu text to be white instead of red.

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/arizona-bootstrap#86]
@camikazegreen commented on [Wed May 20 2020](https://github.com/az-digital/az_quickstart/issues/209)

## Motivation
Current Quickstart 1.0 menus have white text and no underline on the dropdown menus.

### Is your feature request related to a problem? Please describe.
We are trying to match parity of the existing menus.

### Describe the solution you'd like
Normal elements on dropdown menus should have white text and no underline.
Active elements on dropdown menus should be inverted with white backgrounds and Arizona Blue text.

<img width="462" alt="Screen Shot 2020-05-20 at 3 52 42 PM" src="https://user-images.githubusercontent.com/1509771/82505529-d2389080-9ab2-11ea-94a8-6c268a031b31.png">

---

@joshuasosa commented on [Fri Jun 05 2020](https://github.com/az-digital/az_quickstart/issues/209#issuecomment-639821884)

On UA Quickstart, these dropdown menus are styled in UA Bootstrap. In keeping parity, should menu styles be in AZ Bootstrap or in AZ Quickstart? If Bootstrap, then should this issue be moved over to arizona-bootstrap?

---

@camikazegreen commented on [Fri Jun 05 2020](https://github.com/az-digital/az_quickstart/issues/209#issuecomment-639866153)

@joshuasosa We are trying to make sure that all necessary styles or classes are available in Arizona Bootstrap so that it is easier for non-Drupal users to make similar menus. 
I agree that the issue should be moved over to arizona-bootstrap.

**Comment by joeparsons** [comment]
This turned out to be a AZ Quickstart/Barrio issue (az-digital/az_quickstart#209)
