### ISSUE TITLE
Navigation not clickable on Mobile

### ISSUE THREAD

**Issue by HenryzGreenberg** [az-digital/arizona-bootstrap#887]
## Problem/Motivation
Navigation on mobile cannot be reached when the subnavigation has too many items. 

### Describe the bug
I came across this on a development site, I tried to scroll down to the last item in the Mobile navigation and had a hard time getting navigation to show on the page once its does show it cannot be clicked.

### To Reproduce
video example: https://app.screencast.com/pDTc8mB1X2JSD

1. **On an actual mobile device** ( i used iphone 13pro /safari ) goto: https://dev-marcom-redesign.pantheonsite.io/brand-guidelines/videography/filming-campus
2. Click on 'menu' icon in upper right hand corner
3. Click on 'Our Team' at the bottom of the list
5. try to scroll down to "Cross-Campus Leadership"  if you are able to see it try to click on it - https://app.screencast.com/CdwrxSqvunHU7

## Proposed resolution
Description of the proposed solution, the rationale behind it, and workarounds for people who cannot use the patch.

### Expected behavior
Easy to navigate to last items. see Arizona.edu for expected behavior

##  Screenshots
video example: https://app.screencast.com/pDTc8mB1X2JSD

### Smartphone (please complete the following information):
 - Device: [iPhone 13 pro]
 - OS: [iOS 16.6]
 - Browser [chrome and safari]
 - Version [chrome 115 / Safari 17]

**Comment by akslay** [comment]
It looks like this might be specific to iOS devices and not browser specific. I tested on a Pixel 7 Pro with Chrome and was able to expand all of the dropdowns and still click on "Cross-Campus Leadership". You do still get a little bit of background scroll once you reach the bottom of the menu, but the menu item is reachable and intractable.

**Comment by akslay** [comment]
Disregard the above. I had to expand all of the menu items to get the same effect. If I expand 3+ dropdowns, I am unable to see and interact with "Cross-Campus Leadership".

**Comment by trackleft** [comment]
Closed by https://github.com/az-digital/arizona-bootstrap/pull/899
